/*
 * Wikimedia
 * This API provides cacheable and straightforward access to Wikimedia content and data, in machine-readable formats. ### Global Rules - Limit your clients to no more than 200 requests/s to this API.   Each API endpoint's documentation may detail more specific usage limits. - Set a unique `User-Agent` or `Api-User-Agent` header that   allows us to contact you quickly. Email addresses or URLs   of contact pages work well.  By using this API, you agree to Wikimedia's  [Terms of Use](https://wikimediafoundation.org/wiki/Terms_of_Use) and [Privacy Policy](https://wikimediafoundation.org/wiki/Privacy_policy). Unless otherwise specified in the endpoint documentation below, content accessed via this API is licensed under the [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/)  and [GFDL](https://www.gnu.org/copyleft/fdl.html) licenses, and you irrevocably agree to release modifications or additions made through this API under these licenses.  See https://www.mediawiki.org/wiki/REST_API for background and details. ### Endpoint documentation Please consult each endpoint's documentation for details on: - Licensing information for the specific type of content   and data served via the endpoint. - Stability markers to inform you about development status and   change policy, according to   [our API version policy](https://www.mediawiki.org/wiki/API_versioning). - Endpoint specific usage limits. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Availability
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Availability {
  public static final String SERIALIZED_NAME_IN_THE_NEWS = "in_the_news";
  @SerializedName(SERIALIZED_NAME_IN_THE_NEWS)
  private List<String> inTheNews = new ArrayList<>();

  public static final String SERIALIZED_NAME_MOST_READ = "most_read";
  @SerializedName(SERIALIZED_NAME_MOST_READ)
  private List<String> mostRead = new ArrayList<>();

  public static final String SERIALIZED_NAME_ON_THIS_DAY = "on_this_day";
  @SerializedName(SERIALIZED_NAME_ON_THIS_DAY)
  private List<String> onThisDay = new ArrayList<>();

  public static final String SERIALIZED_NAME_PICTURE_OF_THE_DAY = "picture_of_the_day";
  @SerializedName(SERIALIZED_NAME_PICTURE_OF_THE_DAY)
  private List<String> pictureOfTheDay = new ArrayList<>();

  public static final String SERIALIZED_NAME_TODAYS_FEATURED_ARTICLE = "todays_featured_article";
  @SerializedName(SERIALIZED_NAME_TODAYS_FEATURED_ARTICLE)
  private List<String> todaysFeaturedArticle = new ArrayList<>();

  public Availability() {
  }

  public Availability inTheNews(List<String> inTheNews) {
    
    
    
    
    this.inTheNews = inTheNews;
    return this;
  }

  public Availability addInTheNewsItem(String inTheNewsItem) {
    this.inTheNews.add(inTheNewsItem);
    return this;
  }

   /**
   * domains for wikis with this feature enabled, or [ &#39;*.&lt;project&gt;.org&#39; ] for all wikis in a project
   * @return inTheNews
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "domains for wikis with this feature enabled, or [ '*.<project>.org' ] for all wikis in a project")

  public List<String> getInTheNews() {
    return inTheNews;
  }


  public void setInTheNews(List<String> inTheNews) {
    
    
    
    this.inTheNews = inTheNews;
  }


  public Availability mostRead(List<String> mostRead) {
    
    
    
    
    this.mostRead = mostRead;
    return this;
  }

  public Availability addMostReadItem(String mostReadItem) {
    this.mostRead.add(mostReadItem);
    return this;
  }

   /**
   * domains for wikis with this feature enabled, or [ &#39;*.&lt;project&gt;.org&#39; ] for all wikis in a project
   * @return mostRead
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "domains for wikis with this feature enabled, or [ '*.<project>.org' ] for all wikis in a project")

  public List<String> getMostRead() {
    return mostRead;
  }


  public void setMostRead(List<String> mostRead) {
    
    
    
    this.mostRead = mostRead;
  }


  public Availability onThisDay(List<String> onThisDay) {
    
    
    
    
    this.onThisDay = onThisDay;
    return this;
  }

  public Availability addOnThisDayItem(String onThisDayItem) {
    this.onThisDay.add(onThisDayItem);
    return this;
  }

   /**
   * domains for wikis with this feature enabled, or [ &#39;*.&lt;project&gt;.org&#39; ] for all wikis in a project
   * @return onThisDay
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "domains for wikis with this feature enabled, or [ '*.<project>.org' ] for all wikis in a project")

  public List<String> getOnThisDay() {
    return onThisDay;
  }


  public void setOnThisDay(List<String> onThisDay) {
    
    
    
    this.onThisDay = onThisDay;
  }


  public Availability pictureOfTheDay(List<String> pictureOfTheDay) {
    
    
    
    
    this.pictureOfTheDay = pictureOfTheDay;
    return this;
  }

  public Availability addPictureOfTheDayItem(String pictureOfTheDayItem) {
    this.pictureOfTheDay.add(pictureOfTheDayItem);
    return this;
  }

   /**
   * domains for wikis with this feature enabled, or [ &#39;*.&lt;project&gt;.org&#39; ] for all wikis in a project
   * @return pictureOfTheDay
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "domains for wikis with this feature enabled, or [ '*.<project>.org' ] for all wikis in a project")

  public List<String> getPictureOfTheDay() {
    return pictureOfTheDay;
  }


  public void setPictureOfTheDay(List<String> pictureOfTheDay) {
    
    
    
    this.pictureOfTheDay = pictureOfTheDay;
  }


  public Availability todaysFeaturedArticle(List<String> todaysFeaturedArticle) {
    
    
    
    
    this.todaysFeaturedArticle = todaysFeaturedArticle;
    return this;
  }

  public Availability addTodaysFeaturedArticleItem(String todaysFeaturedArticleItem) {
    this.todaysFeaturedArticle.add(todaysFeaturedArticleItem);
    return this;
  }

   /**
   * domains for wikis with this feature enabled, or [ &#39;*.&lt;project&gt;.org&#39; ] for all wikis in a project
   * @return todaysFeaturedArticle
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "domains for wikis with this feature enabled, or [ '*.<project>.org' ] for all wikis in a project")

  public List<String> getTodaysFeaturedArticle() {
    return todaysFeaturedArticle;
  }


  public void setTodaysFeaturedArticle(List<String> todaysFeaturedArticle) {
    
    
    
    this.todaysFeaturedArticle = todaysFeaturedArticle;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Availability instance itself
   */
  public Availability putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Availability availability = (Availability) o;
    return Objects.equals(this.inTheNews, availability.inTheNews) &&
        Objects.equals(this.mostRead, availability.mostRead) &&
        Objects.equals(this.onThisDay, availability.onThisDay) &&
        Objects.equals(this.pictureOfTheDay, availability.pictureOfTheDay) &&
        Objects.equals(this.todaysFeaturedArticle, availability.todaysFeaturedArticle)&&
        Objects.equals(this.additionalProperties, availability.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inTheNews, mostRead, onThisDay, pictureOfTheDay, todaysFeaturedArticle, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Availability {\n");
    sb.append("    inTheNews: ").append(toIndentedString(inTheNews)).append("\n");
    sb.append("    mostRead: ").append(toIndentedString(mostRead)).append("\n");
    sb.append("    onThisDay: ").append(toIndentedString(onThisDay)).append("\n");
    sb.append("    pictureOfTheDay: ").append(toIndentedString(pictureOfTheDay)).append("\n");
    sb.append("    todaysFeaturedArticle: ").append(toIndentedString(todaysFeaturedArticle)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("in_the_news");
    openapiFields.add("most_read");
    openapiFields.add("on_this_day");
    openapiFields.add("picture_of_the_day");
    openapiFields.add("todays_featured_article");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("in_the_news");
    openapiRequiredFields.add("most_read");
    openapiRequiredFields.add("on_this_day");
    openapiRequiredFields.add("picture_of_the_day");
    openapiRequiredFields.add("todays_featured_article");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Availability
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Availability.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Availability is not found in the empty JSON string", Availability.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Availability.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the required json array is present
      if (jsonObj.get("in_the_news") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("in_the_news").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `in_the_news` to be an array in the JSON string but got `%s`", jsonObj.get("in_the_news").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("most_read") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("most_read").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `most_read` to be an array in the JSON string but got `%s`", jsonObj.get("most_read").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("on_this_day") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("on_this_day").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `on_this_day` to be an array in the JSON string but got `%s`", jsonObj.get("on_this_day").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("picture_of_the_day") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("picture_of_the_day").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `picture_of_the_day` to be an array in the JSON string but got `%s`", jsonObj.get("picture_of_the_day").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("todays_featured_article") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("todays_featured_article").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `todays_featured_article` to be an array in the JSON string but got `%s`", jsonObj.get("todays_featured_article").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Availability.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Availability' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Availability> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Availability.class));

       return (TypeAdapter<T>) new TypeAdapter<Availability>() {
           @Override
           public void write(JsonWriter out, Availability value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Availability read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Availability instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Availability given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Availability
  * @throws IOException if the JSON string is invalid with respect to Availability
  */
  public static Availability fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Availability.class);
  }

 /**
  * Convert an instance of Availability to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

